### ISSUE TITLE
Qt open script dialog don't refresh it content

### ISSUE THREAD

**Issue by pirogronian** [CelestiaFork/celestia#42]
Qt open script dialog is "empty", or, more precisely, is filled with standard celestia window content. By moving the dialog around, content "tearing". This issue was present in official repo, but then disappeared, not sure when and why. I just checked, that wip-glwidget branch don't solve this.

**Comment by 375gnu** [comment]
What DE (if any) do you use? I've never had such issues with Xfce4.12 and without DE.

**Comment by pirogronian** [comment]
LXDE 0.9.3
glinfo:

GL_VERSION: 3.3.0 NVIDIA 340.107
GL_RENDERER: GeForce 8600M GT/PCIe/SSE2
GL_VENDOR: NVIDIA Corporation
GL_EXTENSIONS: 
(...)
GL_SHADING_LANGUAGE_VERSION = 3.30 NVIDIA via Cg compiler
GLU_VERSION: 1.3
GLU_EXTENSIONS: GLU_EXT_nurbs_tessellator GLU_EXT_object_space_tess 
GLUT_API_VERSION: 4
GLUT_XLIB_IMPLEMENTATION: 13

glxinfo:

server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
(...)
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
(...)
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 128 MB
    Total available memory: 128 MB
    Currently available dedicated video memory: 104 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce 8600M GT/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.107
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
(...)
OpenGL version string: 3.3.0 NVIDIA 340.107
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)

**Comment by 375gnu** [comment]
Probably, I never liked Gnome :) Unfortunately I know nothing about Qt<->Gtk interaction.

**Comment by pirogronian** [comment]
Solved by configuring qt properly.
