### ISSUE TITLE
Update 3rd party libraries for windows builds

### ISSUE THREAD

**Issue by 375gnu** [CelestiaFork/celestia#46]
Update 3rd party libraries for windows builds, they are outdated.

**Comment by pirogronian** [comment]
Stuff inside windows subdirectory? I can try to compile and test Celestia under Wine, but I don't know, how to get fresh versions of all these libraries. I know dlls, but what are .lib files?

**Comment by 375gnu** [comment]
On 11/9/18, pirogronian <notifications@github.com> wrote:

> Stuff inside windows subdirectory? I can try to compile and test Celestia
> under Wine, but I don't know, how to get fresh versions of all these
> libraries. I know dlls, but what are .lib files?

I believe *.lib files are created by Visual Studio when you compile
those *.dll from sources (they are provided by upstream usually). I
tried to cross-compile using mingw on GNU/Linux, and after some
additional steps had success, but Celestia was unable to start in
Windows VM. With Qt5 build on Windows I'm unable to start it due to
different mingw versions used to compile Celestia and Qt5. Such a
mess.

**Comment by pirogronian** [comment]
Using cmake could help with this (I'm still in stuck with cmake documentation)?

**Comment by 375gnu** [comment]
On 11/10/18, pirogronian <notifications@github.com> wrote:
> Using cmake could help with this (I'm still in stuck with cmake
> documentation)?

Nope.

**Comment by 375gnu** [comment]
superseded with vcpkg
